---
title: Clash Royale Data Model
---

erDiagram

    fct_battle {
        string battle_id PK
        datetime battle_time FK
        integer arena_id FK
        integer game_mode_id FK
        string winner_id FK
        string loser_id FK
        integer winner_starting_trophies
        integer winner_trophies_gained
        integer winner_crowns
        integer loser_starting_trophies
        integer loser_trophies_lost
        integer loser_crowns
    }

    dim_player {
        string player_tag FK
        string player_name 
        integer exp_level
        integer trophies
        integer best_trophies
        integer wins
        integer losses
        integer battle_count
        integer three_crown_wins
        string clan_tag FK
        string role 
    }

    dim_date {
        timestamp battle_time
        year year
        month month
        day day
        hour hour
        minute minute
        second second
    }
    
    br_battle_cards {
        string battle_id FK
        string player_tag FK
        integer card_id FK
        integer card_level 
    }

    dim_cards {
        integer card_id FK
        string name
        int max_level
        int max_evolution_level
        int elixir_cost
    }

    dim_clan {
        string clan_tag FK
        string clan_name
        string type
        string description
        integer clan_score
        integer clan_war_trophies
        integer required_trophies
        integer members
        integer location_id
        string location_name
        boolean is_country
    }

    fct_battle ||--|{ dim_player : ""
    fct_battle ||--|{ dim_date : ""
    dim_player ||--|{ dim_clan : ""
    fct_battle ||--|| br_battle_cards : ""
    dim_cards }|--|| br_battle_cards : ""
    dim_player ||--|{ br_battle_cards : ""
    
